Remove unnecessary components and dependencies
mapswipe/manager-dashboard pull request #1
Opened 2022-07-20 05:21 UTC by frozenhelium

2022-07-20 09:39 UTC, tnagorra requested changes

2022-07-20 09:39 UTC, tnagorra commented on app/index.html
> +            Manager Dashboard needs JS.
You do not need to change this. It's automatically set by webpack.

2022-07-20 09:39 UTC, tnagorra commented on app/index.html
> +        <title>MapSwipe Manager Dashboard</title>
You do not need to change this. It's automatically set by webpack.

2022-07-20 09:39 UTC, tnagorra commented on app/components/Modal/index.tsx
> +                                    name="Close"
Let's add a title prop

2022-08-01 10:03 UTC, tnagorra requested changes

2022-08-01 10:03 UTC, tnagorra commented on app/Base/configs/firebase.ts
> +    firebaseApp = initializeApp(firebaseConfig);
Let's also add a log if we try to init twice.

2022-08-01 10:03 UTC, tnagorra commented on app/Base/components/Navbar/index.tsx
> +            await auth.signOut();
Let's handle loading state

2022-08-01 10:03 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +    );
Can we instead wrap change handlers?

2022-08-01 10:03 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +    );
Can we instead wrap change handlers?

2022-08-01 10:03 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +        console.info(finalValues);
Let's handle this

2022-08-05 09:32 UTC, laurentS reviewed
Can I simply suggest that you setup a very basic CI check (with github actions to stay consistent with the other repos) that does linting and type checking at a minimum? I cannot figure out if you've picked a formatter, but I'd strongly recommend it if not (and check formatting in CI).
In my experience, doing this early helps quite a lot, and is very cheap.
EDIT: ignore me, I just saw the checks below. well done :)

2022-08-05 11:06 UTC, tnagorra commented
Hi @laurentS 

Thanks for the reminder about the CI/CD.

We have implemented a simple CI pipeline that includes:
- test runner
- code linting
- build check

You can take a look at the current progress and play around in our test environment at https://mapswipe-manager-dashboard.dev.togglecorp.com. It uses the dev mapswipe firebase instance.

cc: @Hagellach37 @danbjoseph

2022-08-08 05:52 UTC, tnagorra commented
Let's also rename "Organization" to "Organisation" through out the project.

2022-08-08 06:51 UTC, tnagorra requested changes

2022-08-08 06:51 UTC, tnagorra commented on app/components/FileInput/index.tsx
> +        };
It's better if we could use similar mechanism to GeoJSON Input

2022-08-08 06:51 UTC, tnagorra commented on app/components/FileInput/index.tsx
> +    const [inputId] = React.useState(randomString());
```suggestion
    const [inputId] = React.useState(() => randomString());
```

2022-08-08 06:51 UTC, tnagorra commented on app/components/GeoJsonFileInput/index.tsx
> +function readUploadedFileAsText(inputFile: File) {
Let's move this to utils

2022-08-08 06:51 UTC, tnagorra commented on app/components/GeoJsonPreview/index.tsx
> +                );
Let's check why this does not load in locally hosted server

2022-08-08 06:51 UTC, tnagorra commented on app/hooks/useFirebaseDatabase.tsx
> +        return unsubscribe;
We may need to include `setPending(false)` when unsubscribing.

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/index.tsx
> +            const list = Object.entries(userGroups ?? {});
```suggestion
            const list = Object.entries(userGroups) ?? [];
```

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/UserGroupItem/index.tsx
> +                    setArchivePending(false);
We need to check if it's mounted here as well. The catch block can run after an async function throws

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/UserGroupItem/index.tsx
> +            }
Let's return early.
Why are we iterating on memberIds and adding onValue handlers? Is this to listen for change?

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/UserGroupFormModal/index.tsx
> +                setSubmissionStatus('failed');
We need to check if it's mounted here as well. The catch block can run after an async function throws

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/UserGroupFormModal/index.tsx
> +                        }
Let's return early.

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/UserGroupFormModal/index.tsx
> +                            setSubmissionStatus('success');
Check if it's mounted after await

2022-08-08 06:51 UTC, tnagorra commented on app/views/UserGroups/UserGroupFormModal/index.tsx
> +                        const newKey = newUserGroupRef.key;
Check if it's still mounted after await

2022-08-08 06:51 UTC, tnagorra commented on app/views/Teams/index.tsx
> +    const teamList = Object.entries(teams ?? {});
```suggestion
    const teamList = Object.entries(teams) ?? [];
```

2022-08-08 06:51 UTC, tnagorra commented on app/views/Teams/TeamItem/index.tsx
> +    const teamMemberList = Object.entries(teamMembers ?? {});
```suggestion
    const teamMemberList = teamMembers ? Object.entries(teamMembers) : [];
```

2022-08-08 06:51 UTC, tnagorra commented on app/views/NewProject/utils.ts
> +    return `${projectTopic} - ${projectRegion}(${projectNumber}) ${requestingOrganisation}`;
```suggestion
    return `${projectTopic} - ${projectRegion} (${projectNumber}) ${requestingOrganisation}`;
```

2022-08-08 06:51 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +                }
We should use ternary operator instead

2022-08-08 06:51 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +                }
We should use ternary operator instead

2022-08-08 06:51 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +    /*
Let's remove this

2022-08-08 06:51 UTC, tnagorra commented on app/views/NewProject/index.tsx
> +                        placeholder="[Project Topic] - [Project Region]([Task Number]) [Requesting Organisation]"
```suggestion
                        placeholder="[Project Topic] - [Project Region] ([Task Number]) [Requesting Organisation]"
```

2022-08-08 06:51 UTC, tnagorra commented on app/views/Login/index.tsx
> +    const handleLoginClick = React.useCallback(async () => {
Lets use useMountedRef here

2022-08-08 06:51 UTC, tnagorra commented on app/Base/components/Navbar/index.tsx
> +    const handleLogoutClick = React.useCallback(async () => {
Let's add useMountedRef

2022-08-09 04:15 UTC, tnagorra commented on app/components/GeoJsonPreview/index.tsx
> +                    4,
bump

2022-08-09 04:16 UTC, tnagorra commented on app/components/GeoJsonPreview/index.tsx
> +                );
bump

2022-08-09 04:16 UTC, tnagorra commented on app/components/GeoJsonPreview/index.tsx
> +            if (mapRef.current) {
bump

2022-08-09 04:16 UTC, tnagorra commented on app/components/GeoJsonPreview/index.tsx
> +                if (geoJsonLayerRef.current && mapRef.current) {
bump

2022-08-09 04:19 UTC, frozenhelium commented on app/components/GeoJsonPreview/index.tsx
> +                );
We'll be changing the tile layer, so let's ignore this one for now

2022-08-09 04:24 UTC, frozenhelium commented on app/views/UserGroups/UserGroupItem/index.tsx
> +            }
Fetching details for all users that belong in the group, there isn't any better way :/

2022-08-09 05:49 UTC, merged